# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kalco < Formula
  desc "Kubernetes Analysis & Lifecycle Control - Extract, validate, analyze, and version control your entire cluster"
  homepage "https://github.com/graz-dev/kalco"
  version "0.1.8"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/graz-dev/kalco/releases/download/v0.1.8/kalco_Darwin_x86_64.tar.gz"
      sha256 "b3142192e4af59da9aa4e14dcdb8010315bd544db610eed7a3813898f71f5e49"

      def install
        bin.install "kalco"
      end
    end
    on_arm do
      url "https://github.com/graz-dev/kalco/releases/download/v0.1.8/kalco_Darwin_arm64.tar.gz"
      sha256 "785bab9c7a60db6ba4790d0052ee2cb5ef6229fd45df5fbf317bd9d03f138c99"

      def install
        bin.install "kalco"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/graz-dev/kalco/releases/download/v0.1.8/kalco_Linux_x86_64.tar.gz"
        sha256 "081ec568b55ee1844385b8ee12ff93b547037e70925fab800242a19c1d5b6598"

        def install
          bin.install "kalco"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/graz-dev/kalco/releases/download/v0.1.8/kalco_Linux_arm64.tar.gz"
        sha256 "2488302edc3bda3f316c2a7e67e81899ab3e6e18917be3b0ab2c003523fb63cb"

        def install
          bin.install "kalco"
        end
      end
    end
  end

  test do
    system "#{bin}/kalco --help"
  end
end
