# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kalco < Formula
  desc "Kubernetes Analysis & Lifecycle Control - Extract, validate, analyze, and version control your entire cluster"
  homepage "https://github.com/graz-dev/kalco"
  version "0.1.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/graz-dev/kalco/releases/download/v0.1.4/kalco_Darwin_x86_64.tar.gz"
      sha256 "7ca03579bd880587ef9ed1f22c60d2b31ccc46124c812ae25083266df6d38592"

      def install
        bin.install "kalco"
      end
    end
    on_arm do
      url "https://github.com/graz-dev/kalco/releases/download/v0.1.4/kalco_Darwin_arm64.tar.gz"
      sha256 "35110b4da8511d35f645e20d154888b2406ce186669e2208c3797a373e4eb93a"

      def install
        bin.install "kalco"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/graz-dev/kalco/releases/download/v0.1.4/kalco_Linux_x86_64.tar.gz"
        sha256 "3575c7297a23b769bd61044fb38e3d30128d19afea39015a2d6089bbd48bb46c"

        def install
          bin.install "kalco"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/graz-dev/kalco/releases/download/v0.1.4/kalco_Linux_arm64.tar.gz"
        sha256 "30579493b0c12350284ff3aa46a15272164b24a58a4dbd298721d9d34376e65f"

        def install
          bin.install "kalco"
        end
      end
    end
  end

  test do
    system "#{bin}/kalco --help"
  end
end
