# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kalco < Formula
  desc "Kubernetes Analysis & Lifecycle Control - Extract, validate, analyze, and version control your entire cluster"
  homepage "https://github.com/graz-dev/kalco"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/graz-dev/kalco/releases/download/v0.1.7/kalco_Darwin_x86_64.tar.gz"
      sha256 "426d530952fdd008fea5adb3418faabf97029825d79d2aaba80f1ea68a1e4019"

      def install
        bin.install "kalco"
      end
    end
    on_arm do
      url "https://github.com/graz-dev/kalco/releases/download/v0.1.7/kalco_Darwin_arm64.tar.gz"
      sha256 "3a0aa7c94d24820aafe26ac07d4787ed379fc0291f38cd05f25c37d4ffcefe5d"

      def install
        bin.install "kalco"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/graz-dev/kalco/releases/download/v0.1.7/kalco_Linux_x86_64.tar.gz"
        sha256 "5a94be9f1195d6963e0c14a569c96850d8c89b9d76ff30768d415161341a723c"

        def install
          bin.install "kalco"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/graz-dev/kalco/releases/download/v0.1.7/kalco_Linux_arm64.tar.gz"
        sha256 "6659486ebf14fa6a7a966d7b69e0c164242ca66110fa4ee348f2c241796bfb02"

        def install
          bin.install "kalco"
        end
      end
    end
  end

  test do
    system "#{bin}/kalco --help"
  end
end
